package com.example.mycityapp.ui.theme

import androidx.compose.ui.graphics.Color

//light color palette
val md_theme_light_primary = Color(0xFF4D6700)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCF077)
val md_theme_light_onPrimaryContainer = Color(0xFF151F00)
val md_theme_light_secondary = Color(0xFF406918)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBFF190)
val md_theme_light_onSecondaryContainer = Color(0xFF0D2000)
val md_theme_light_tertiary = Color(0xFF1D6C30)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFA5F5A9)
val md_theme_light_onTertiaryContainer = Color(0xFF002107)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFCF4)
val md_theme_light_onBackground = Color(0xFF1B1C17)
val md_theme_light_surface = Color(0xFFFEFCF4)
val md_theme_light_onSurface = Color(0xFF1B1C17)
val md_theme_light_surfaceVariant = Color(0xFFE2E4D4)
val md_theme_light_onSurfaceVariant = Color(0xFF45483C)
val md_theme_light_outline = Color(0xFF76786B)
val md_theme_light_inverseOnSurface = Color(0xFFF2F1E9)
val md_theme_light_inverseSurface = Color(0xFF30312C)
val md_theme_light_inversePrimary = Color(0xFFB0D35E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4D6700)

//dark color palette
val md_theme_dark_primary = Color(0xFFB0D35E)
val md_theme_dark_onPrimary = Color(0xFF263500)
val md_theme_dark_primaryContainer = Color(0xFF394D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFCCF077)
val md_theme_dark_secondary = Color(0xFFA4D577)
val md_theme_dark_onSecondary = Color(0xFF1B3700)
val md_theme_dark_secondaryContainer = Color(0xFF295000)
val md_theme_dark_onSecondaryContainer = Color(0xFFBFF190)
val md_theme_dark_tertiary = Color(0xFF89D88F)
val md_theme_dark_onTertiary = Color(0xFF003911)
val md_theme_dark_tertiaryContainer = Color(0xFF00531D)
val md_theme_dark_onTertiaryContainer = Color(0xFFA5F5A9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1C17)
val md_theme_dark_onBackground = Color(0xFFE4E3DB)
val md_theme_dark_surface = Color(0xFF1B1C17)
val md_theme_dark_onSurface = Color(0xFFE4E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF45483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C8B8)
val md_theme_dark_outline = Color(0xFF909284)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1C17)
val md_theme_dark_inverseSurface = Color(0xFFE4E3DB)
val md_theme_dark_inversePrimary = Color(0xFF4D6700)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB0D35E)


val seed = Color(0xFFA3C552)