package com.example.mycityapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF804796)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF9D8FF)
val md_theme_light_onPrimaryContainer = Color(0xFF320046)
val md_theme_light_secondary = Color(0xFF745B00)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFE08B)
val md_theme_light_onSecondaryContainer = Color(0xFF241A00)
val md_theme_light_tertiary = Color(0xFF4F6600)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCAF160)
val md_theme_light_onTertiaryContainer = Color(0xFF161F00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF190261)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF190261)
val md_theme_light_surfaceVariant = Color(0xFFEBDFE9)
val md_theme_light_onSurfaceVariant = Color(0xFF4C444D)
val md_theme_light_outline = Color(0xFF7D747D)
val md_theme_light_inverseOnSurface = Color(0xFFF4EEFF)
val md_theme_light_inverseSurface = Color(0xFF2F2176)
val md_theme_light_inversePrimary = Color(0xFFECB1FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF804796)

val md_theme_dark_primary = Color(0xFFECB1FF)
val md_theme_dark_onPrimary = Color(0xFF4D1464)
val md_theme_dark_primaryContainer = Color(0xFF662E7C)
val md_theme_dark_onPrimaryContainer = Color(0xFFF9D8FF)
val md_theme_dark_secondary = Color(0xFFF1C100)
val md_theme_dark_onSecondary = Color(0xFF3D2F00)
val md_theme_dark_secondaryContainer = Color(0xFF584400)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE08B)
val md_theme_dark_tertiary = Color(0xFFAED446)
val md_theme_dark_onTertiary = Color(0xFF273500)
val md_theme_dark_tertiaryContainer = Color(0xFF3B4D00)
val md_theme_dark_onTertiaryContainer = Color(0xFFCAF160)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF190261)
val md_theme_dark_onBackground = Color(0xFFE5DEFF)
val md_theme_dark_surface = Color(0xFF190261)
val md_theme_dark_onSurface = Color(0xFFE5DEFF)
val md_theme_dark_surfaceVariant = Color(0xFF4C444D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC3CD)
val md_theme_dark_outline = Color(0xFF988E97)
val md_theme_dark_inverseOnSurface = Color(0xFF190261)
val md_theme_dark_inverseSurface = Color(0xFFE5DEFF)
val md_theme_dark_inversePrimary = Color(0xFF804796)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFECB1FF)


val seed = Color(0xFF804796)


